sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: TQoa3KL8Ac7Nfq5wqCcKsKXl21bGo5rcDAqDkUme4icF9MGHLrUimShpO5C+aWydLtpBXV/Egm9fHFv4JcWgZHZ02v9HbZgisqIcfOFfhuExEU+wJAQ2A+79V6Un9+Los4ywAsGnX2f7TxD8C800TknShYgyJach+O8XgO9C1bDeAOf/3NAFu++wlbECZ30dnQEPd2Ju6TwLp2+6UXVwGBa8i13nvKtirPiCXHptrtnfUz0C/UANsCz7RA8OvfAkSIQZWiNQcH35fLpTYlDWwA6ZU9XCz/SJzt02HdchVp5BcK3w7gFJ9/rdnFS94Z0cPHpljr15DaRHYA6x7HL4d8QPKRwtBnCPyGSl8Zw+ZpPiRE4+x0MMVMb6iTyQD2+Z4Ah2Cwcss+QxnLFZCxLJKzuHttXql78j5031uvvujM9YRpPumAPj5p2BDbqIt8CO3EXRffHtt4UFdcoiov9vYH4xL16my2BXLnfXYgGOs9SPicH5QM6uAlN7kkno37icfUZHyU7Ptr5iXr6I0LHCr0oAfMOhKAEjq4XstZU/LzFuCWN6/PiNReF2XWXXBk5uLQFq6sFKJ+e2jdImxOiGnnx26Mgo2xlGdKBi1Fe2coH0qZOuE2sTXtZyqIbhTAn0RGWWiB5y8JgTDepB1bUIj7XadQ/dDasWxTWP8uqupdE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/An-Outcast-of-the-Islands_638
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy